name: flutter_hackathon_2023
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

  # For Architecture
  flutter_hooks: 0.18.6
  hooks_riverpod: 2.4.1
  async: 2.11.0

  # For Record
  record: ^4.4.4

  # For Model
  json_serializable: 6.7.1
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # For Key-Value local storage
  shared_preferences: 2.2.1

  # For UIs
  auto_route: 7.8.3
  gap: 3.0.1
  cached_network_image: 3.3.0
  visibility_detector: 0.4.0+2
  sliver_tools: 0.2.12
  flutter_svg: 2.0.7
  go_router: ^11.1.2
  decorated_icon: 1.2.1
  stop_watch_timer: 3.0.2
  collection: any

  # For data manipulation
  built_collection: 5.1.1
  dartx: 1.2.0

  # For Audio
  audioplayers: 5.1.0

  # For Environment variables
  flutter_dotenv: ^5.1.0

  # For Supabase
  supabase_flutter: ^1.10.19

  # For Splash
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For Lint
  flutter_lints: 2.0.3
  flutter_hooks_lint_plugin: 0.6.1

  # For Model
  freezed: 2.4.1

  build_runner: 2.4.6
  flutter_gen_runner: 5.3.2
  auto_route_generator: 7.3.1

  # For Splash
  flutter_native_splash: ^2.1.3+1

  # For Icon
  flutter_launcher_icons: ^0.9.2

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/icon/
    - assets/audio/
    - shorebird.yaml

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ios_icon_1024.png"
  adaptive_icon_foreground: "assets/icon/android_icon_512.png"
  adaptive_icon_background: "#EEEEEE"

flutter_native_splash:
  background_image: 'assets/icon/splash_background.png'
  fullscreen: true