name: Check Source Code
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ synchronize, opened, reopened ]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1.2.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: 'flutter-:channel:-:version:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:'
      - name: Install fvm
        run: dart pub global activate fvm
      - name: Install Flutter
        run: fvm install
      - name: Get Packages
        run: make pub
      - name: Run Build Runner
        run: make build run
      - name: Run Analyze
        run: fvm flutter analyze
